name: Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]  # update setiap hari jam 00:00 UTC
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # token GitHub classic
          user: azzanslebew

          # 📺 Anime List
          plugin_anilist: yes
          plugin_anilist_user: "azzanisham"
          plugin_anilist_medias: anime
          plugin_anilist_sections: watching
