name: Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]  # update setiap hari jam 00:00 UTC
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # token GitHub classic
          user: azzanslebew

          # Basic Overview
          base: header, activity, community, repositories
          config_timezone: Asia/Jakarta

          # 🔥 Language & Coding Line Stats
          plugin_languages: yes
          plugin_languages_ignored: html
          plugin_languages_details: lines, percentage
          plugin_lines: yes

          # 📈 Habit Tracker
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # 🎥 YouTube Latest Video
          plugin_posts: yes
          plugin_posts_source: youtube
          plugin_posts_limit: 2
          plugin_posts_user: UCNalweapOFwBm7O_m7en_TA  # GANTI DENGAN YOUTUBE CHANNEL ID
          plugin_posts_token: ${{ secrets.AIzaSyACxm9Mt6RC3AH3qtPD_0WmTAjEhalAQoE }}

          # 📺 Anime List
          plugin_anilist: yes
          plugin_anilist_user: "azzanisham"
          plugin_anilist_medias: anime
          plugin_anilist_sections: watching
