name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # jalan setiap hari jam 00:00 UTC
  workflow_dispatch:     # bisa dijalankan manual juga

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: azzanslebew
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
