name: 🕒 WakaTime Readme Stats

on:
  schedule:
    - cron: '0 5 * * *' # update setiap jam 12:00 WIB
  workflow_dispatch:

jobs:
  update-readme:
    name: WakaTime Graph Update
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_TITLE: true
          SHOW_TOTAL: true
          TIME_RANGE: last_7_days
          LANG_COUNT: 5
          SHOW_TIME: true
          SHOW_MASKED_TIME: false
