name: 🕒 WakaTime Readme Stats

on:
  schedule:
    - cron: '0 5 * * *' # setiap hari jam 12:00 WIB
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Optional features (gunakan hanya yang valid)
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_EDITORS: true
          SHOW_LANGUAGE: true
          SHOW_TIMEZONE: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_LINES_OF_CODE: true
          SHOW_COMMIT: true
          SHOW_TOTAL_CODE_TIME: true
